org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true
org.gradle.configuration-cache=true

# Meta
mod.id=universal_vault
mod.name=Universal Vault
mod.group=com.mrchuw.universalvault
mod.version=1.1.0
mod.description=Global and personal vaults with I/O, commands and keybinds.
mod.authors=MrChuw
mod.repo_url=https://github.com/MrChuw/universalvault
mod.license=GPLv2
mod.logo=assets/universal_vault/icon.png

# Loader deps comuns
deps.fabric-loader=0.19.5

# Publish
publish.curseforge=
publish.modrinth=
